name: My5G-RANTester Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.10
        
      - name: Check Versions
        run: |
          lsb_release -a
          uname -a
          go version
          git --version
          docker --version
          echo "pwd: $(pwd)"
          echo "GOROOT: $GOROOT"
          echo "GOPATH: $GOPATH"
          echo "Listing dirs"
          ls -la
          sudo ln -s $GOROOT /usr/local/go
          
      - name: Install Go Deps
        run: go mod download

      - name: Build my5g-RANTester
        run: go build ./cmd/my5g-RANTester
